### ISSUE TITLE
Dp6 language

### ISSUE THREAD

**Issue by bangbuiduc** [d6lts/elysia_cron#1]
file: elysia_cron.admin.inc
$ipath = url(drupal_get_path('module', 'elysia_cron') . '/images/icon_'); => /vi/sites/...
=> $ipath = file_create_url(drupal_get_path('module', 'elysia_cron') . '/images/icon_');

**Comment by dsnopek** [comment]
Unfortunately, I don't really understand this report. If you comment back with some more details, I'd be happy to re-open this issue, but for not I'm closing.
